-- ============================================================================
-- Home Health SnowDay Demo - Environment Setup
-- ============================================================================
-- This script sets up the database, schemas, and roles for the Home Health DME demo
-- IMPORTANT: Run this script as ACCOUNTADMIN
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- 1. Create Database
CREATE OR REPLACE DATABASE HOME_HEALTH_DEMO
COMMENT = 'Home Health DME Analytics Demo - Denials, Sales, Call Center';

USE DATABASE HOME_HEALTH_DEMO;

-- 2. Create Schemas (Medallion Architecture)
CREATE OR REPLACE SCHEMA RAW_DATA
COMMENT = 'Raw data ingested from source systems (claims, CRM, phone systems)';

CREATE OR REPLACE SCHEMA TRANSFORMED
COMMENT = 'Cleaned and transformed data via Dynamic Tables';

CREATE OR REPLACE SCHEMA ANALYTICS
COMMENT = 'Analytics views, KPIs, and semantic models';

CREATE OR REPLACE SCHEMA DOCUMENTS
COMMENT = 'Policy documents for Cortex Search';

-- 3. Create Roles (Home Health Organizational Structure)
CREATE OR REPLACE ROLE BILLING_ADMIN
COMMENT = 'Revenue cycle and denials management team';

CREATE OR REPLACE ROLE SALES_MANAGER
COMMENT = 'Sales leadership and territory management';

CREATE OR REPLACE ROLE CALL_CENTER_LEAD
COMMENT = 'Call center operations and workforce management';

CREATE OR REPLACE ROLE ANALYST
COMMENT = 'Cross-functional analytics and reporting';

CREATE OR REPLACE ROLE DATA_ENGINEER
COMMENT = 'Data pipeline and infrastructure management';

CREATE OR REPLACE ROLE EXECUTIVE
COMMENT = 'C-suite executive access to all KPIs';

-- 4. Role Hierarchy
GRANT ROLE BILLING_ADMIN TO ROLE EXECUTIVE;
GRANT ROLE SALES_MANAGER TO ROLE EXECUTIVE;
GRANT ROLE CALL_CENTER_LEAD TO ROLE EXECUTIVE;
GRANT ROLE ANALYST TO ROLE EXECUTIVE;
GRANT ROLE EXECUTIVE TO ROLE SYSADMIN;
GRANT ROLE DATA_ENGINEER TO ROLE SYSADMIN;

-- 5. Database Permissions
GRANT USAGE ON DATABASE HOME_HEALTH_DEMO TO ROLE BILLING_ADMIN;
GRANT USAGE ON DATABASE HOME_HEALTH_DEMO TO ROLE SALES_MANAGER;
GRANT USAGE ON DATABASE HOME_HEALTH_DEMO TO ROLE CALL_CENTER_LEAD;
GRANT USAGE ON DATABASE HOME_HEALTH_DEMO TO ROLE ANALYST;
GRANT USAGE ON DATABASE HOME_HEALTH_DEMO TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE HOME_HEALTH_DEMO TO ROLE EXECUTIVE;

-- Schema Permissions
GRANT ALL ON SCHEMA RAW_DATA TO ROLE DATA_ENGINEER;
GRANT ALL ON SCHEMA TRANSFORMED TO ROLE DATA_ENGINEER;
GRANT ALL ON SCHEMA ANALYTICS TO ROLE DATA_ENGINEER;
GRANT ALL ON SCHEMA DOCUMENTS TO ROLE DATA_ENGINEER;

GRANT USAGE ON SCHEMA RAW_DATA TO ROLE BILLING_ADMIN;
GRANT USAGE ON SCHEMA TRANSFORMED TO ROLE BILLING_ADMIN;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE BILLING_ADMIN;

GRANT USAGE ON SCHEMA RAW_DATA TO ROLE SALES_MANAGER;
GRANT USAGE ON SCHEMA TRANSFORMED TO ROLE SALES_MANAGER;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE SALES_MANAGER;

GRANT USAGE ON SCHEMA ANALYTICS TO ROLE CALL_CENTER_LEAD;
GRANT USAGE ON SCHEMA TRANSFORMED TO ROLE CALL_CENTER_LEAD;

GRANT USAGE ON SCHEMA ANALYTICS TO ROLE ANALYST;
GRANT USAGE ON SCHEMA TRANSFORMED TO ROLE ANALYST;
GRANT USAGE ON SCHEMA RAW_DATA TO ROLE ANALYST;

GRANT USAGE ON SCHEMA ANALYTICS TO ROLE EXECUTIVE;
GRANT USAGE ON SCHEMA TRANSFORMED TO ROLE EXECUTIVE;

-- 6. Create Warehouses
CREATE OR REPLACE WAREHOUSE HOME_HEALTH_LOAD_WH
WITH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = 'STANDARD'
COMMENT = 'Data loading and ETL operations';

CREATE OR REPLACE WAREHOUSE HOME_HEALTH_ANALYTICS_WH
WITH
    WAREHOUSE_SIZE = 'LARGE'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 5
    SCALING_POLICY = 'STANDARD'
COMMENT = 'Analytics, dashboards, and AI workloads';

CREATE OR REPLACE WAREHOUSE HOME_HEALTH_ADHOC_WH
WITH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'ECONOMY'
COMMENT = 'Ad-hoc queries and exploration';

-- 7. Warehouse Permissions
GRANT USAGE ON WAREHOUSE HOME_HEALTH_LOAD_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HOME_HEALTH_ANALYTICS_WH TO ROLE BILLING_ADMIN;
GRANT USAGE ON WAREHOUSE HOME_HEALTH_ANALYTICS_WH TO ROLE SALES_MANAGER;
GRANT USAGE ON WAREHOUSE HOME_HEALTH_ANALYTICS_WH TO ROLE CALL_CENTER_LEAD;
GRANT USAGE ON WAREHOUSE HOME_HEALTH_ANALYTICS_WH TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE HOME_HEALTH_ANALYTICS_WH TO ROLE EXECUTIVE;
GRANT USAGE ON WAREHOUSE HOME_HEALTH_ADHOC_WH TO ROLE ANALYST;

-- 8. Verify Setup
SHOW DATABASES LIKE 'HOME_HEALTH_DEMO';
SHOW SCHEMAS IN DATABASE HOME_HEALTH_DEMO;
SHOW ROLES LIKE 'BILLING%';
SHOW ROLES LIKE 'SALES%';
SHOW ROLES LIKE 'CALL%';
SHOW WAREHOUSES LIKE 'HOME_HEALTH%';

-- 9. Set Context
USE ROLE DATA_ENGINEER;
USE DATABASE HOME_HEALTH_DEMO;
USE SCHEMA RAW_DATA;
USE WAREHOUSE HOME_HEALTH_LOAD_WH;

SELECT '✅ ENVIRONMENT SETUP COMPLETE' as status;
